### ISSUE TITLE
Thank you and a question

### ISSUE THREAD

**Issue by virtualandy** [samkelleher/P3ColorSpaceExperiments#1]
Sam,

Have been trying to read up on color profiles and sharp, so thanks for putting this together. Saved me a bunch of time!

I'm wondering if you ever found a good solution to this:
> So we should detect and preserve images that have been exported using P3.

Either with sharp and libvips or something else.

Thanks!

**Comment by samkelleher** [comment]
Hi @virtualandy ,

In the end I focused my testing around using Sharp, and started talking on a ticket on their repo regarding a `toColorSpace` method (https://github.com/lovell/sharp/issues/218)

Using Sharp does an unnecessary conversion form P3 to sRGB during processing and requires work done there to prevent this from happening. That's as far as I got, although it's still on my TODO to pick this up as I still need to implement P3 on the project I'm working on, just giving Sharp some time to implement it since P3 usage is probably stlll relatively low.

**Comment by virtualandy** [comment]
@samkelleher thanks for the follow up and extra info. In our case, we probably _want_ to do a P3 -> sRGB conversion so might be good to go. But we also want to preserve originals and may want to do additional processing on those via sharp and keep the profile info, so maybe we also just wait there.

Anyway, thanks again!

**Comment by wanna2014go** [comment]
> 嗨@virtualandy，
> 
> 最后，我将测试重点放在了使用Sharp上，并开始在他们的回购单上谈论一种`toColorSpace`方法（[lovell / sharp＃218](https://github.com/lovell/sharp/issues/218)）
> 
> 使用Sharp会在处理过程中进行从P3到sRGB的不必要的转换，并且需要在那里做一些工作来防止这种情况的发生。那是我所能得到的，尽管我仍然需要在正在从事的项目上实施P3，但仍需要我在TODO上进行，只是给了夏普一些时间来实施它，因为P3的使用率可能相对较低。
I'm wondering if you ever found a good solution to this?
